name: Lint Shell Scripts

on:
  pull_request:
    branches:
      - main
      - master
jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: ShellCheck
        uses: koalaman/shellcheck-action@v2
        with:
          files: '**/*.sh'
          
